bootstrap.memory_lock: false
network.host: 0.0.0.0
discovery.zen.minimum_master_nodes: 1
discovery.type: single-node
http.port: 9200
cluster.name: elasticsearch
node.data: true
node.ingest: true
node.master: true
node.max_local_storage_nodes: 1
node.name: mydocker_node1
transport.tcp.port: 9300
xpack.license.self_generated.type: basic
xpack.security.enabled: false
